# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FourMoneyBears' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FourMoneyBears

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'SCLAlertView'
  pod 'EMTNeumorphicView'
  pod 'Macaw', '0.9.6'
end
